### ISSUE TITLE
fuel reprocessing don't respond on first click

### ISSUE THREAD

**Issue by confusingbits** [confusingbits/KSPInterstellar#40] opened 2014-09-08 00:26 UTC
You have to click the fuel reprocessor twice to get it started.

**Comment by Poofey** [comment] 2014-09-14 09:30
how exactly twice? i can't get the science lab to reprocess at all. the most i get it to do is display processing for a fraction of a second before returning to idle if i click the button whilst the game is paused, but no actual processing is done.

**Comment by confusingbits** [comment] 2014-09-14 09:37
You can't ever click anything with the pause menu up, so I have no idea what you are talking about there.

If reprocessing isn't working, you likely have a bad install or you don't have tank for uranium to place the depleted uranium.

**Comment by Poofey** [comment] 2014-09-14 09:55
re installed, version 12.3. Have 1600 space for less than 100 actinides plus about the same ratio of uranium to refuel, reactor is shut down and showing EVA maintenance needed, the science lab shows the reprocess button but clicking it only makes the "closing" animation to play, even if the lab is already "closed". 
by the pause menu, i meant bring up the menu, pause then click the button, unpause and the word processing pops up for a microsecond before returning to idle.
the tanks are in a ship docked to the station that has the reactor, if it makes any difference.

**Comment by confusingbits** [comment] 2014-09-14 10:02
Have you tried clicking it twice while not paused, cause that it is bug. You have to click it twice because it doesn't respond the first time. Just spam the reprocess button until it starts.

I still don't know how you are able to interact with the UI with the game paused, that is not a thing that is supposed to happen. You will also need power to reprocess fuel.

**Comment by Poofey** [comment] 2014-09-14 10:05
it still had a bit of power left when i tried, it has none now. I'll replenish the power and try again. 
I did spam the button btw, but it hurts no one to try again. 
The UI interacting whilst paused is a ksp thing, i can do it with every button you can even get a crew report while paused.

edit: well, i had no mercy on my mouse, at about 10-15 clicks it finally reacted. but yeah twice doesn't cut it for me, hope it helps tracking down the bug.

partially unrelated question: is the reprocessing working only on active vessels (meaning the process stops if i switch out) intended behavior?

**Closed as completed** 2016-08-17 00:21 UTC
Labels: bug
